# Generated by Django 5.2.5 on 2025-09-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_profile_pic_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purok',
            field=models.TextField(blank=True, null=True),
        ),
    ]
